apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db-instance.cz80kas6a7cn.eu-west-1.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db-instance.cz80kas6a7cn.eu-west-1.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db-instance.cz80kas6a7cn.eu-west-1.rds.amazonaws.com/userdb
  orderdb_url:  mongodb+srv://admin:pass_2525@atlas-cluster.pmiyzew.mongodb.net//?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka


  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  